version: 2                                       # 1/2/2.1の何れかを指定。バージョンによって記述の仕方が異なるので注意（現状であれば、2,2.1のどちらかが推奨みたい
jobs:                                            # 必須固定
  build:                                         # Job名/Jobが1つの場合は必ず"build:"
    docker:                                      # ビルド環境(machine/macosなどのVPCを選ぶことも可能だけど、dockerが主流みたい
      - image: circleci/node:8.16.1                # ビルドイメージを指定。firebaseCLIはnode.js ver6.0.0以上推奨であることを確認しつつ、現在のnode.js推奨バージョンである10を指定
    steps:                                       # 実行内容記述開始の合図
      - run:                                     # firebaseCLI入れる前に念のためnpmバージョンチェック
          name: 'npm version check'
          command: node -v
      - run:
          name: package install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy  --except functions -P mlpj-d9574 --token=$FIREBASE_TOKEN # プロジェクト上のfirebase-toolsでデプロイします                
workflows:                                       # 定義したJobを流すフローを指定
  version: 2
  build_and_deploy:                              # 任意のフロー名でOK
    jobs:                                        # 実行Jobを配下に記述
      - build:                                   # 今回は”build"のみなので、これだけ！あまりフローを組む必要性ないですけど、必須みたいです！
          filters:
            branches:
              only: master 