version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.1-browsers
    steps:
      - checkout
      - run:
          name: 'node version check'
          command: node -v
      - run:
          name: package install
          command: yarn install
      - run:
          name: build
          command: yarn build
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --except functions -P mlpj-d9574 --token=$FIREBASE_TOKEN
  st:
    docker:
      - image: circleci/node:8.16.1
    steps:
      - checkout
      - run:
          name: 'staging'
          command: node -v                          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          context: test
          filters:
            branches:
              only: master
      - st:
          context: test
          filters:
            branches:
              only: staging